services:
  ticketing-system:
    build:
      context: ticketing-system
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - APP_DATABASE__HOST=postgres
      - APP_DATABASE__PASSWORD=${POSTGRES_PASSWORD:-password}
      - APP_DATABASE__DATABASE_NAME=${POSTGRES_DB:-ticketing_system}
      - APP_DATABASE__PORT=${POSTGRES_PORT:-5432}
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_REDIS__URL=redis://redis:6379
      - APP_STORAGE__TYPE=filesystem
      - APP_STORAGE__BASE_PATH=./storage
      - APP_STORAGE__BASE_URL=/storage
      - APP_APPLICATION__BASE_URL=${APP_BASE_URL:-127.0.0.1}
    volumes:
      - files_storage:/app/server/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:alpine
    command: redis-server --save 900 1 --save 300 10 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ticketing_system}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx-fs.conf:/etc/nginx/nginx.conf
      - ./www/build:/usr/share/nginx/html
      - files_storage:/var/www/files
    depends_on:
      ticketing-system:
        condition: service_healthy

volumes:
  redis_data:
  pg_data:
  minio_data:
  files_storage: