services:
  ticketing-system:
    build:
      context: ticketing-system
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - APP_DATABASE__HOST=postgres
      - APP_DATABASE__PASSWORD=${POSTGRES_PASSWORD:-password}
      - APP_DATABASE__DATABASE_NAME=${POSTGRES_DB:-ticketing_system}
      - APP_DATABASE__PORT=${POSTGRES_PORT:-5432}
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_REDIS__URL=redis://redis:6379
      - APP_STORAGE__REGION=us-east-1
      - APP_STORAGE__ENDPOINT=http://minio:9000
      - APP_STORAGE__ACCESS_KEY=some_access_key
      - APP_STORAGE__SECRET_KEY=some_secret_key
      - APP_STORAGE__BUCKET=${S3_BUCKET:-ticketing-attachments}
      - APP_APPLICATION__BASE_URL=${APP_BASE_URL:-127.0.0.1}
      - APP_EMAIL_CLIENT__BASE_URL=http://email-mock-server:8080
      - APP_EVENT_PUBLISHER__BASE_URL=http://event-mock-server:8080
      - APP_EVENT_PUBLISHER__BOT_TOKEN=1
      - APP_EVENT_PUBLISHER__CHAT_ID=1
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      start_period: 15s
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:17.6
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ticketing_system}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_INITDB_ARGS="-c max_connections=1000"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
      - ./www/build:/usr/share/nginx/html
    depends_on:
      ticketing-system:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      /usr/bin/mc mb myminio/${S3_BUCKET:-ticketing-attachments} --ignore-existing;
      /usr/bin/mc mb myminio/${S3__PRIVATE_BUCKET:-private-attachments} --ignore-existing;
      /usr/bin/mc policy set public myminio/${S3_BUCKET:-ticketing-attachments};
      /usr/bin/mc admin user svcacct add --access-key some_access_key --secret-key some_secret_key myminio ${MINIO_ROOT_USER:-minioadmin} || true;
      exit 0;
      "
    restart: "no"

  email-mock-server:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./infra/wiremock/email/mappings:/home/wiremock/mappings
      - ./infra/wiremock/email/__files:/home/wiremock/__files
    command: --global-response-templating --verbose
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  event-mock-server:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./infra/wiremock/event/mappings:/home/wiremock/mappings
      - ./infra/wiremock/event/__files:/home/wiremock/__files
    command: --global-response-templating --verbose
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pg_data:
  minio_data: