services:
  ticketing-system:
    image: ghcr.io/blackravenoo/ticketing-system
    build:
      context: ticketing-system
      dockerfile: Dockerfile
    environment:
      - APP_DATABASE__HOST=postgres
      - APP_DATABASE__PASSWORD=${POSTGRES_PASSWORD:-password}
      - APP_DATABASE__DATABASE_NAME=${POSTGRES_DB:-ticketing_system}
      - APP_DATABASE__PORT=${POSTGRES_PORT:-5432}
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_REDIS__URL=redis://redis:6379
      - APP_STORAGE__REGION=${S3_REGION:-us-east-1}
      - APP_STORAGE__ENDPOINT=${S3_ENDPOINT}
      - APP_STORAGE__ALWAYS_PROXY=${S3_ALWAYS_PROXY:-false}
      - APP_STORAGE__ACCESS_KEY=${S3_ACCESS_KEY}
      - APP_STORAGE__SECRET_KEY=${S3_SECRET_KEY}
      - APP_STORAGE__PATH_STYLE=false
      - APP_STORAGE__BUCKET=${S3_BUCKET:-ticketing-attachments}
      - APP_APPLICATION__BASE_URL=${APP_BASE_URL:-127.0.0.1}
      - APP_EMAIL_CLIENT__BASE_URL=https://api.mailersend.com
      - APP_EMAIL_CLIENT__SENDER_EMAIL=${SENDER_EMAIL}
      - APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN=${EMAIL_CLIENT_TOKEN}
      - APP_EVENT_PUBLISHER__BASE_URL=https://api.telegram.org
      - APP_EVENT_PUBLISHER__BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - APP_EVENT_PUBLISHER__CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:alpine
    command: redis-server --save 900 1 --save 300 10 --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ticketing_system}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ticketing_system}
      interval: 15s
      timeout: 5s
      retries: 5

  nginx:
    image: ghcr.io/blackravenoo/nginx-ticketing
    build:
      context: .
      dockerfile: infra/Dockerfile-nginx
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      ticketing-system:
        condition: service_healthy
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  redis_data:
  pg_data: