services:
  ticketing-system:
    build:
      context: ticketing-system
      dockerfile: Dockerfile
    environment:
      - APP_DATABASE__HOST=postgres
      - APP_DATABASE__PASSWORD=${POSTGRES_PASSWORD:-password}
      - APP_DATABASE__DATABASE_NAME=${POSTGRES_DB:-ticketing_system}
      - APP_DATABASE__PORT=${POSTGRES_PORT:-5432}
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_REDIS__URL=redis://redis:6379
      - APP_STORAGE__REGION=${S3_REGION:-us-east-1}
      - APP_STORAGE__ENDPOINT=${S3_ENDPOINT}
      - APP_STORAGE__ALWAYS_PROXY=false
      - APP_STORAGE__ACCESS_KEY=${S3_ACCESS_KEY}
      - APP_STORAGE__SECRET_KEY=${S3_SECRET_KEY}
      - APP_STORAGE__PATH_STYLE=false
      - APP_STORAGE__BUCKET=${S3_BUCKET:-ticketing-attachments}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 20s
      retries: 3


  redis:
    image: redis:alpine
    command: redis-server --save 900 1 --save 300 10 --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ticketing_system}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
      - ./www/build_tmp:/usr/share/nginx/html
    depends_on:
      ticketing-system:
        condition: service_healthy

volumes:
  redis_data:
  pg_data: